server:
  port: 8080

spring:
  application:
    name: hong-coding-gateway
  cloud:
    gateway:
      routes:
        - id: content_route
          uri: lb://hong-coding-content
          predicates:
            - Path=/api/articles/**,/api/categories/**
          filters:
            - StripPrefix=1
            
        - id: user_route
          uri: lb://hong-coding-user
          predicates:
            - Path=/api/users/**,/api/auth/**
          filters:
            - StripPrefix=1
            
        - id: search_route
          uri: lb://hong-coding-search
          predicates:
            - Path=/api/search/**
          filters:
            - StripPrefix=1 