# ======================
# 服务基础配置
# ======================
server:
  # 服务监听端口
  port: 8080


# ======================
# Spring 应用配置
# ======================
spring:
  main:
    web-application-type: reactive
  application:
    # 微服务注册名称（用于服务发现标识）
    name: hong-coding-gateway

  # ======================
  # Spring Cloud 组件配置
  # ======================
  cloud:
    # Nacos 服务治理配置
    nacos:
      discovery:
        # 服务注册中心地址（格式：IP:Port）
        server-addr: 117.72.84.26:8848
      config:
        # 配置中心地址（格式：IP:Port） 
        server-addr: 117.72.84.26:8848
        namespace: public

    # ======================
    # API 网关核心配置
    # ======================
    gateway:
      discovery:
        locator:
          # 开启服务发现自动路由（根据服务名自动创建路由）
          enabled: true
          lower-case-service-id: true
#      globalcors:
#        cors-configurations:
#          '[/**]':
#            allowedOrigins: "*"
#            allowedMethods:
#              - "*"
#            allowedHeaders: "*"
      routes:
        # ----------------------
        # 内容服务路由规则
        # - uri: 负载均衡协议 + 目标服务名
        # - predicates: 路径匹配规则（支持Ant风格）
        # - filters: 
        #   - StripPrefix: 去除请求路径前缀（数字表示去除的层级）
        #   - AddRequestHeader: 添加自定义请求头
        # ----------------------
#        - id: auth_route
#          uri: lb://hong-coding-auth
#          predicates:
#            - Path=/auth/**
#          filters:
#            - StripPrefix=1
#
        - id: content_route
          uri: lb://hong-coding-content
          predicates:
            - Path=/api/articles/**,/api/categories/**
          filters:
            - StripPrefix=1
#            - AddRequestHeader=X-Request-From, Gateway
            
        # ----------------------
        # 用户服务路由规则
        # ----------------------
        - id: user_route
          uri: lb://hong-coding-user
          predicates:
            - Path=/api/**
          filters:
            - StripPrefix=1
#            - AddRequestHeader=X-Request-From, Gateway
            
        # ----------------------
        # 搜索服务路由规则
        # ----------------------
#        - id: search_route
#          uri: lb://hong-coding-search
#          predicates:
#            - Path=/api/search/**
#          filters:
#            - StripPrefix=1
#            - AddRequestHeader=X-Request-From, Gateway

    # ======================
    # Sentinel 流量治理配置
    # ======================
    sentinel:
      transport:
        dashboard: localhost:8856 # Sentinel 控制台地址
        port: 8719 # Sentinel 与控制台通信的端口
      eager: true # 开启 Sentinel 自动加载
#      datasource:
#        ds1: # 数据源名称
#          nacos: # 使用 Nacos 作为规则数据源
#            server-addr: 117.72.84.26:8848 # Nacos 服务地址
#            dataId: ${spring.application.name}-sentinel-rules # 规则数据 ID
#            groupId: DEFAULT_GROUP # 规则数据分组
#            rule-type: gw-flow # 规则类型，这里是网关流量规则

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.cloud.loadbalancer: DEBUG
    reactor.netty: DEBUG